export type BookType = "epub" | "pdf" | "word" | "txt" | "ppt" | "excel" | "html";
export type BookCategory = string;

export interface Book {
  id: string;
  title: string;
  author: string;
  cover: string;
  coverColor: string;
  type: BookType;
  category: BookCategory;
  progress: number;
  totalPages: number;
  currentPage: number;
  addedDate: string;
  lastRead?: string;
  size: string;
  description: string;
  tags: string[];
  isFavorite: boolean;
  isDemo?: boolean;
  genStatus?: "pending" | "fetching" | "planning" | "cover" | "writing" | "reviewing" | "publishing" | "done" | "failed" | "no_book";
  sourceType?: "github" | "file" | "url" | "youtube";
  coverHtml?: string;
  sourceUrl?: string;
}

export const books: Book[] = [
  {
    id: "1",
    title: "百年孤独",
    author: "加西亚·马尔克斯",
    cover: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=200&h=280&fit=crop&auto=format",
    coverColor: "#8B4513",
    type: "epub",
    category: "fiction",
    progress: 68,
    totalPages: 422,
    currentPage: 287,
    addedDate: "2024-01-15",
    lastRead: "2024-03-10",
    size: "2.3 MB",
    description: "魔幻现实主义文学的巅峰之作，布恩迪亚家族七代人的传奇故事。",
    tags: ["诺贝尔奖", "魔幻现实主义", "经典"],
    isFavorite: true,
    isDemo: true,
  },
  {
    id: "2",
    title: "设计心理学",
    author: "唐纳德·诺曼",
    cover: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=280&fit=crop&auto=format",
    coverColor: "#2C5F8A",
    type: "pdf",
    category: "nonfiction",
    progress: 100,
    totalPages: 368,
    currentPage: 368,
    addedDate: "2023-11-20",
    lastRead: "2024-02-28",
    size: "8.1 MB",
    description: "探讨日常事物的设计原则，改变你对设计的思考方式。",
    tags: ["设计", "心理学", "用户体验"],
    isFavorite: false,
    isDemo: true,
  },
  {
    id: "3",
    title: "三体",
    author: "刘慈欣",
    cover: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=200&h=280&fit=crop&auto=format",
    coverColor: "#1a3a4a",
    type: "epub",
    category: "fiction",
    progress: 32,
    totalPages: 600,
    currentPage: 192,
    addedDate: "2024-02-01",
    lastRead: "2024-03-08",
    size: "3.7 MB",
    description: "中国科幻文学里程碑，描绘人类与三体文明的宏大史诗。",
    tags: ["科幻", "雨果奖", "中国文学"],
    isFavorite: true,
    isDemo: true,
  },
  {
    id: "4",
    title: "深度工作",
    author: "卡尔·纽波特",
    cover: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=200&h=280&fit=crop&auto=format",
    coverColor: "#3d5a3e",
    type: "epub",
    category: "nonfiction",
    progress: 55,
    totalPages: 296,
    currentPage: 163,
    addedDate: "2024-01-08",
    lastRead: "2024-03-05",
    size: "1.8 MB",
    description: "在信息爆炸时代，如何专注创造真正的价值。",
    tags: ["生产力", "专注", "职业发展"],
    isFavorite: false,
    isDemo: true,
  },
  {
    id: "5",
    title: "人类简史",
    author: "尤瓦尔·赫拉利",
    cover: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=200&h=280&fit=crop&auto=format",
    coverColor: "#6b4226",
    type: "pdf",
    category: "nonfiction",
    progress: 88,
    totalPages: 512,
    currentPage: 451,
    addedDate: "2023-09-12",
    lastRead: "2024-01-20",
    size: "12.4 MB",
    description: "从认知革命到人工智能，重新审视人类的过去与未来。",
    tags: ["历史", "人类学", "畅销书"],
    isFavorite: true,
    isDemo: true,
  },
  {
    id: "6",
    title: "Q4产品规划报告",
    author: "产品团队",
    cover: "",
    coverColor: "#4a4a6a",
    type: "word",
    category: "documents",
    progress: 100,
    totalPages: 45,
    currentPage: 45,
    addedDate: "2024-03-01",
    lastRead: "2024-03-12",
    size: "3.2 MB",
    description: "2024年第四季度产品路线图与功能规划文档。",
    tags: ["工作", "产品", "规划"],
    isFavorite: false,
    isDemo: true,
  },
  {
    id: "7",
    title: "机器学习实战",
    author: "奥雷利安·杰龙",
    cover: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=200&h=280&fit=crop&auto=format",
    coverColor: "#2d4a6b",
    type: "pdf",
    category: "academic",
    progress: 24,
    totalPages: 738,
    currentPage: 177,
    addedDate: "2024-02-14",
    lastRead: "2024-03-01",
    size: "45.6 MB",
    description: "从理论到实践，系统掌握机器学习核心算法与应用。",
    tags: ["机器学习", "Python", "AI"],
    isFavorite: false,
    isDemo: true,
  },
  {
    id: "8",
    title: "鬼灭之刃 Vol.1",
    author: "吾峠呼世晴",
    cover: "https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=200&h=280&fit=crop&auto=format",
    coverColor: "#8b1a2a",
    type: "epub",
    category: "manga",
    progress: 100,
    totalPages: 192,
    currentPage: 192,
    addedDate: "2023-12-05",
    lastRead: "2023-12-06",
    size: "85.3 MB",
    description: "大正时代，少年炭治郎踏上寻鬼之路，为家人复仇。",
    tags: ["漫画", "动作", "日本"],
    isFavorite: true,
    isDemo: true,
  },
  {
    id: "9",
    title: "年度财务分析报告",
    author: "财务部",
    cover: "",
    coverColor: "#2a5a2a",
    type: "excel",
    category: "documents",
    progress: 0,
    totalPages: 12,
    currentPage: 0,
    addedDate: "2024-03-10",
    size: "1.1 MB",
    description: "2023年度各部门财务数据汇总与分析。",
    tags: ["财务", "工作", "数据"],
    isFavorite: false,
    isDemo: true,
  },
  {
    id: "10",
    title: "活着",
    author: "余华",
    cover: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=200&h=280&fit=crop&auto=format",
    coverColor: "#7a3a2a",
    type: "epub",
    category: "fiction",
    progress: 12,
    totalPages: 188,
    currentPage: 23,
    addedDate: "2024-03-08",
    size: "0.9 MB",
    description: "一部关于苦难与生命意义的震撼之作。",
    tags: ["中国文学", "当代", "经典"],
    isFavorite: false,
    isDemo: true,
  },
  {
    id: "11",
    title: "用户体验要素",
    author: "杰西·加勒特",
    cover: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&h=280&fit=crop&auto=format",
    coverColor: "#3a4a6a",
    type: "pdf",
    category: "academic",
    progress: 76,
    totalPages: 192,
    currentPage: 146,
    addedDate: "2023-10-22",
    lastRead: "2024-02-15",
    size: "6.8 MB",
    description: "以用户为中心的网站设计，从战略到界面的五个层次。",
    tags: ["UX", "设计", "产品"],
    isFavorite: true,
    isDemo: true,
  },
  {
    id: "13",
    title: "CSS权威指南",
    author: "Eric A. Meyer",
    cover: "https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=200&h=280&fit=crop&auto=format",
    coverColor: "#c25b16",
    type: "html",
    category: "academic",
    progress: 41,
    totalPages: 280,
    currentPage: 115,
    addedDate: "2024-01-30",
    lastRead: "2024-03-09",
    size: "4.2 MB",
    description: "深入讲解CSS级联、选择器、布局与动画，是前端开发者的必备参考书。",
    tags: ["CSS", "前端", "Web开发"],
    isFavorite: false,
    isDemo: true,
  },
  {
    id: "12",
    title: "2024Q1产品发布PPT",
    author: "产品团队",
    cover: "",
    coverColor: "#6a3a6a",
    type: "ppt",
    category: "documents",
    progress: 100,
    totalPages: 32,
    currentPage: 32,
    addedDate: "2024-03-05",
    lastRead: "2024-03-11",
    size: "15.2 MB",
    description: "2024年第一季度新产品发布演示文稿。",
    tags: ["工作", "产品", "演示"],
    isFavorite: false,
    isDemo: true,
  },
];

export const categories = [
  { id: "all", label: "全部", icon: "BookOpen", count: books.length },
  { id: "fiction", label: "文学小说", icon: "BookMarked", count: books.filter(b => b.category === "fiction").length },
  { id: "nonfiction", label: "非虚构", icon: "Lightbulb", count: books.filter(b => b.category === "nonfiction").length },
  { id: "academic", label: "学术专业", icon: "GraduationCap", count: books.filter(b => b.category === "academic").length },
  { id: "documents", label: "文档资料", icon: "FileText", count: books.filter(b => b.category === "documents").length },
  { id: "manga", label: "漫画", icon: "Smile", count: books.filter(b => b.category === "manga").length },
  { id: "generated", label: "AI 生成", icon: "BookOpen", count: books.filter(b => b.category === "generated").length },
];

export const typeConfig: Record<BookType, { label: string; color: string; bg: string }> = {
  epub: { label: "EPUB", color: "#3d6b8a", bg: "#e8f0f7" },
  pdf: { label: "PDF", color: "#8a3d3d", bg: "#f7e8e8" },
  word: { label: "WORD", color: "#2d6a8a", bg: "#e2f0f7" },
  txt: { label: "TXT", color: "#5a5a5a", bg: "#f0f0f0" },
  ppt: { label: "PPT", color: "#8a5a2d", bg: "#f7f0e2" },
  excel: { label: "XLSX", color: "#2d7a4a", bg: "#e2f5ec" },
  html: { label: "HTML", color: "#c25b16", bg: "#fdf0e8" },
};
